name: Rust

on: [workflow_dispatch]
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: "https://registry.npmjs.org"
        scope: "@nealrame"
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: wasm-pack build --scope nealrame
    - name: Publish
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}